### ISSUE TITLE
ModernMT is missing from the MT providers' list in MateCat

### ISSUE THREAD

**Issue by mzeidhassan** [matecat/MateCat#1153]
Hi @Ostico,

I hope I receive an answer to my question.

I have installed the open-source version of MateCat, but I don't even see ModernMT is listed there as an option. Any idea why? Please see the screen shot enclosed.

Thanks,
Mohamed
![screenshot from 2017-11-10 13-35-00](https://user-images.githubusercontent.com/7589948/36884959-567a776e-1da1-11e8-9ee8-3990c55482dd.png)

**Comment by Ostico** [comment]
Hi @mzeidhassan 
you must add this configuration on the config.ini in order to activate MMT:

```
MANDATORY_PLUGINS[] = 'mmt'
```

**Comment by Ostico** [comment]
Hi @mzeidhassan 
yes at moment you have to buy a subscription for ModernMT service we offer because the ModernMT enterprise API layer ( connected with MateCat ) is different from the ModernMT open source API.

ModernMT is an open source software of course, but at moment there is no a driver for the free open source version that you can install in house. We are working to offer this driver.

Please refer to @davidecaroselli for any further info on that.
