### ISSUE TITLE
lib/Model/matecat.sql causes Field 'id_dqf_project' doesn't have a default value error.

### ISSUE THREAD

**Issue by YourLittleHelper** [matecat/MateCat#1208]
Sql file lib/Model/matecat.sql defines `segments.id_dqf_project` as NOT NULL field, but later in script tries to insert row into segments table without id_dqf_proejct field defined causing `ERROR 1364 (HY000) at line 1189: Field 'id_dqf_project' doesn't have a default value.` error

**Comment by Ostico** [comment]
Hi @YourLittleHelper ,
Please refer to this for MySQL configuration:
https://github.com/matecat/MateCat/issues/599

**Comment by burglarhobbit** [comment]
@Ostico Even after making the changes in MySQL configuration, the error remains.

What I did was, I added 
```[mysqld]
sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION``` 

in the `/etc/mysql/my.cnf` file

**Comment by burglarhobbit** [comment]
@YourLittleHelper  The only solution for this issue is to install the MySQL 5.5.50 version (from source) as its the MySQL version of the VM. Newer MySQL versions are unable to successfully execute the .sql script.

@Ostico

**Comment by Ostico** [comment]
@burglarhobbit @YourLittleHelper , this is not the only solution, it is not the solution in my opionion because we use mysql 5.7.

I found the issue, the error is in the sql which pre-populate the database, this row is wrong:
https://github.com/matecat/MateCat/blob/develop/INSTALL/matecat.sql#L1189

it lacks of `id_dqf_project` when inserting the row because, as @YourLittleHelper says, it is defined as NOT NULL value.

We will change it as soon as possible, sorry.

**Comment by burglarhobbit** [comment]
@Ostico Alright. Thanks for the heads up.

**Comment by Ostico** [comment]
Fixed
