### ISSUE TITLE
The Auto-Propagate dialogue proposes no hotkeys

### ISSUE THREAD

**Issue by felixvd** [matecat/MateCat#16]
It forces a mouse move and click every time it comes up and steals time during big jobs. Cmd+Enter and Escape respectively might be good hotkeys.

**Comment by antoniofarina** [comment]
I agree on the use of "Esc" to close (and, hence, refuse to autpropagate): we will integrate in the next release

The hotkey to accept to autopropagate is dangerous because the action is very invasive and has no undo chance so we ask the translator to tick explicitly the checkbox in order to allow him to click "Yes".

**Comment by felixvd** [comment]
A fair argument. 

Hotkeys for the error selection would probably save more mouse movement anyway. I'll make another issue of that if a good setup comes to mind.
