### ISSUE TITLE
MySQL Data saving + Updates

### ISSUE THREAD

**Issue by Alf71** [matecat/MateCat#3]
Hi

So, the translation units are saved into MySQL

Is it possible to run MySQL and save its DATA in a different system using Windows?
A kind of tunneling?

Will you consider using SQLITE in the future?

The second question is: How easy it is, to update MateCat to a newer version?
Over the linux command line?

Best regards!

Alf

**Comment by matecat** [comment]
Hi Alf,
at moment, any other kind of storage system different from MySQL is not on the road map because of hard tuning we have done on queries ( MySQL dialect ) and data structures. This kind of compatibility layer is a very big effort and at the moment we have more relevant tasks to complete.

Moreover, surely SQLITE wìill be not used because of it's intrinsic limitation ( single thread connection, single user, and consequently lacks of transactions ).

Regarding the software updates, by the next release ( 0.4.2.4 ) we will provide a bash script and a documented procedure to update the software from previous versions.

This procedure/script will be improved gradually with subsequent releases.
