### ISSUE TITLE
Outdated Installation Guide at Configure MySql

### ISSUE THREAD

**Issue by NumBerNanA** [matecat/MateCat#3365]
from https://site.matecat.com/installation-guide#confmysql
I Paste the new configuration to /etc/mysql/mysql.conf.d/mysqld.cnf
and i can't  restart service
![ภาพ](https://github.com/matecat/MateCat/assets/9784404/11bc31dd-d389-44a4-9370-2d3362be91ff)

my sql version 
![ภาพ](https://github.com/matecat/MateCat/assets/9784404/9936a7b9-c385-4329-b170-15cd8d0bfa0c)

**Comment by NumBerNanA** [comment]
error when i in put stetting

`query_cache_limit = 1M
query_cache_size = 16M`

`gtid_mode = on
enforce_gtid_consistency = true
sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
explicit_defaults_for_timestamp=true`

**Comment by NumBerNanA** [comment]
and at https://site.matecat.com/installation-guide#imc

at command `mysql -u root -p < matecat.sql`

have error
![ภาพ](https://github.com/matecat/MateCat/assets/9784404/313dc17d-70af-4353-87c6-d3a7c47c1cca)

**Comment by trki200068** [comment]
https://github.com/arduino/Arduino.wiki.git

**Comment by NumBerNanA** [comment]
> https://github.com/arduino/Arduino.wiki.git

sorry 404 page not found

**Comment by groundcat** [comment]
I had the same error and it turns out to be a MySQL version issue. It's perhaps only compatible with MySQL 5.7. 

I followed this guide and successfully installed it on Ubuntu 20. 

1. Follow the steps up to Step 1.5 here https://www.devart.com/dbforge/mysql/how-to-install-mysql-on-ubuntu/
2. `apt install -f mysql-client=5.7* mysql-server=5.7*`

**Comment by riccio82** [comment]
Updated guide: [https://site.matecat.com/installation-guide](https://site.matecat.com/installation-guide)
