### ISSUE TITLE
ubuntu 14.04 only see white page, virtualbox can not see translation editor

### ISSUE THREAD

**Issue by unasettimana** [matecat/MateCat#377]
Hi,
I'm trying to install the matecat on my own PC in both "Coding" and "Virtualbox" ways:
1, "Coding" way:
I think I'm having the same issue with "MateCat installation #343" and I tried the solution of Ositco for "#54" but I'm stucked with the "Composer.phar", those four command lines never work on my Ubuntu 14.04, php5....I followed some instructions to install composer (created also the composer.json), but when I type "npm install" under "/support_scripts/", I got this:

![screenshot_matecat_1](https://cloud.githubusercontent.com/assets/2707774/18237573/d39e7a48-7365-11e6-84b0-c6d0f98da409.png)

and before that, there was this one:

![screenshot_matecat_2](https://cloud.githubusercontent.com/assets/2707774/18237680/dc883ba2-7366-11e6-9ef9-a695f54bd8a7.png)

So, please I need some help!!!

2, "Virtualbox" way:
I downloaded the '.ova' file and installed on my virtualbox, everything seems to be good but when trying the test docs, after clicked the "translate" button, the browser will give me only this:

![screenshot_matecat_3](https://cloud.githubusercontent.com/assets/2707774/18237815/8f7efef2-7368-11e6-806a-1c73f752cc13.png)

there is no editor...

Any help will be highly appreciated, many thanks ;-)

**Comment by Ostico** [comment]
Hi @unasettimana ,

you have some connection/permission issues, for npm issue, try this:
https://github.com/npm/npm/issues/3664#issuecomment-21050464

For composer issues you should check your connection and/or your dns resolution. Seems that composer can not resolve the address.

**Comment by unasettimana** [comment]
Hi @Ostico ,
Thanks for your reply...I'm wondering if I can have more details about the solutions for issue #343 and #54 ?

**Comment by unasettimana** [comment]
And for the "Virtualbox", can you help to explain why there is no editor visible in translate mode? Thx

**Comment by Ostico** [comment]
@unasettimana, i suppose that you get a white page because javascript is not compiled, so no source is available to download for the browser.

The solution i proposed to @safiaa1 https://github.com/matecat/MateCat/issues/54#issuecomment-215521236 should work also for your issue.

For the virtualbox way:
there is a possibility that the ova is old and it has a bug.

You have 2 possibilities, the first one is to wait at max at the end of this week because we will release a new ova version. The second one is to send to support@matecat.com the version number of your matecat installation and the logs that you can find inside the directory <Virtualbox:/your_matecat_dir>/storage/log_archive/ , the technical support will help you in fix/configure the ova.

**Comment by unasettimana** [comment]
Hi @Ostico , thx for your reply.
1, I already tried your solution to #54 before release this issue, I got those errors of npm and composer...I think what you wrote requires other configurations
2, ok, I'll send the files to the support email

**Comment by unasettimana** [comment]
@Ostico done, thanks!
