### ISSUE TITLE
Failed to store segments in database for $originalFileName

### ISSUE THREAD

**Issue by eclavelr** [matecat/MateCat#414]
@Ostico 

I have followed exactly all the guide provided in http://www.matecat.com/advanced-manual-setup/
But, look what is happen in my instance
![github](https://cloud.githubusercontent.com/assets/18006411/18680768/10053674-7f33-11e6-9f01-30d0e7f0f4fd.png)
In this https://github.com/matecat/MateCat/blob/73f01cc9a95856ff04f0e537ead218e0034877d6/lib/Utils/ProjectManager.php#L446
This exception is thrown in the try {...} catch from https://github.com/matecat/MateCat/blob/73f01cc9a95856ff04f0e537ead218e0034877d6/lib/Utils/ProjectManager.php#L394 to https://github.com/matecat/MateCat/blob/73f01cc9a95856ff04f0e537ead218e0034877d6/lib/Utils/ProjectManager.php#L437

What means code -2? (see https://github.com/matecat/MateCat/blob/73f01cc9a95856ff04f0e537ead218e0034877d6/lib/Utils/ProjectManager.php#L444)
Who is throwing that exception?

I'm trying to figure out what is happening in my installation.

**Comment by Ostico** [comment]
Hi @eclavelr ,

you should check the logs to find the exact  issue, but it is related to:
https://github.com/matecat/MateCat/blob/73f01cc9a95856ff04f0e537ead218e0034877d6/lib/Utils/ProjectManager.php#L433

and specifically to this line:

https://github.com/matecat/MateCat/blob/73f01cc9a95856ff04f0e537ead218e0034877d6/lib/Utils/ProjectManager.php#L1708

**Comment by Ostico** [comment]
I close, reopen if you need more.

**Comment by yifanjiang** [comment]
@eclavelr 

JFYI - When the red background bar with "failed to store... database" shows, it usually means that. 

Something  "Segment import - DB Error:" could be found in log.txt.

This is possibly caused by the updated default mysql_mode set. A newer version of mysql (>5.6) apparently is not in favor of everything in matecat.sql schema :-) For a test environment, I simply did this:

# diff -u /etc/my.cnf.ori /etc/my.cnf  
--- /etc/my.cnf.ori     2016-10-05 17:11:39.970695172 +0800  
+++ /etc/my.cnf 2016-10-05 17:04:29.557161899 +0800  
@@ -55,7 +55,8 @@  
 # sort_buffer_size = 2M  
 # read_rnd_buffer_size = 2M  
  
-sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES  
+#sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES  
+sql_mode=""  

To know more details of this mode:

https://dev.mysql.com/doc/refman/5.6/en/sql-mode.html
http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-changes
