### ISSUE TITLE
Is uploaded TMX private?

### ISSUE THREAD

**Issue by mindaugasDEV** [matecat/MateCat#466]
Hello @Ostico ,

In ticket #455 you answered about the privacy of uploaded Matecat user data the following way:
“Your content is used by us ONLY for statistical and big data analysis. Your private data are not shared in any way.“ 

Please confirm that you (MateCAT, ModernMT or Translated.net teams) do NOT use uploaded TMX for training MT engines or related language work and you don`t give it to third parties .

It would be also reassuring if you could explain what kind of BigData and statistical analysis you do with Matecat users data.

I am sure this question is important for many users that are considering MateCAT OpenSource installations.

Thanks,
Mindaugas

**Comment by Ostico** [comment]
Hello @mindaugasDEV ,

we can confirm that no personal data  ( and TMX contents ) are shared with third parties.

We will ( because at moment we don't ) perform analysis on these data to improve MateCat matches from our TM servers and to improve light auto-corrections ( language localization for dates and punctuation in sentences for example ) of MateCat suggestions to raise the TM scores up to theoretically 100% exact matches.

Moreover, all others related info can be found in the service terms and condition of use page:
http://www.matecat.com/terms/
