### ISSUE TITLE
Bug: We noticed that after translation there's still to-do words and only "preview" option is available

### ISSUE THREAD

**Issue by wsuphappyhour** [matecat/MateCat#476]
Hi,
We noticed that after translation(all segments are approved and revised) there's still to-do words and only "Preview" option is available not "Download Translation".

![image](https://cloud.githubusercontent.com/assets/20355306/19434565/e5198fa4-946e-11e6-92d5-021dd2ef373a.png)

![image](https://cloud.githubusercontent.com/assets/20355306/19434577/f6fcf5bc-946e-11e6-831e-d317259461d8.png)

Thanks!

**Comment by wsuphappyhour** [comment]
This is a serious issue as it appears these ghost words can be only translated with other CAT tool after downloading preview version from MateCat. Is it possible to modify out of the box MateCat version to show full file in the editor view to prevent this issue. As I understand not all segments are displayed in editor view.
Thanks.

**Comment by Ostico** [comment]
Hi @wsuphappyhour ,

this is an issue that usually happens when database is suffering an heavy load and transactions are discarded by database.

By the way, MateCat not shows only segments that are not translatable ( sentences that contains tags only or sentences that contains only punctuation and/or tags ).
