### ISSUE TITLE
Including untranslated segments in Export Job TMX

### ISSUE THREAD

**Issue by pepc** [matecat/MateCat#48]
Currently the Export Job TMX function does not include untranslated segments.

If untranslated segments where available in the exported Job TMX, it would allow for use cases other than QA, such as, doing concordance searches with Xbench among non-translated segments yet.

For larger projects, that helps researching terminology and glossary preparation because you can see all segments in you job where a given term will appear (you do not have to wait until the translation is finished to understand that the term chosen was wrong).

**Comment by alessandrocattelan** [comment]
The Export Job TMX function is intended to let users export a TM with their translated segments only. Adding untranslated segments would result in a TMX file with unedited matches from TM or MT. I am afraid this would not be ideal for MateCat users.

I understand your point about preparing glossaries, I guess one way of solving this could be using an XLIFF export instead of the TMX. However, this is not currently available in MateCat and we will have to postpone this to one of the next releases.

**Comment by pepc** [comment]
What I was having in mind was no target language for the unconfirmed segments (after all, Xbench would treat them as untranslated segments anyway). Also, TMX generation would be a lot faster if TM/MT queries are not run during the TMX export of an unfinished job.

So the proposal really is that confirmed segments would have two languages (source and target) and unconfirmed segments would have just one (source).  This is OK with regards to TMX file validity because TMX files are multilingual so the number of languages in a given segment does not matter (it can be one, two or more).

**Comment by Ostico** [comment]
Done. Will be available on the next release.
