### ISSUE TITLE
New languages in MateCat

### ISSUE THREAD

**Issue by Tatyana1011** [matecat/MateCat#762]
Hello! Our machine translation API has been integrated in MateCat.

I found in your config more languages than available for users. Some of them are disabled, for example Amharic. What is the reason for this? Can we make a pull-request for enabling this languages? 

The second question. Can we make a pull-request for adding new languages, that you haven't got at all in your config (Mari, Hill Mari, Bashkir and Papiamento)?

**Comment by Ostico** [comment]
Of course, all PR are welcome.
We will make a review on such PR to verify that adding new languages will not break anything on our side also. 

If all will be ok we will accept the pull requests.

Please, submit your pull requests on the develop branch.

Regarding the first question, some languages are not available because they are not tested.
Furthermore, all the language codes in the language file MUST be reviewed because the majority are wrong. Some names and codes have been changed for the newest/less used languages.

**Comment by Tatyana1011** [comment]
Thanks! :)

**Comment by Ostico** [comment]
Published. 
https://github.com/matecat/MateCat/releases/tag/v1.3.0
Close
