### ISSUE TITLE
Leading spaces are trimmed where they should not

### ISSUE THREAD

**Issue by robot-xliff-farmer** [matecat/MateCat#847]
Matecat replaces by a single space all leading spaces in the segments which have xml:space="preserve" attribute, e.g. DITA codeblocks.
Attached is a zip with two test files: the source .dita and .xlf generated by Matecat-filters.
[Archive.zip](https://github.com/matecat/MateCat/files/1128612/Archive.zip)
Spaces are OK after Matecat-filters so it seems that the problem is in Matecat.

**Comment by freegenie** [comment]
MateCat doesn't do anything special with xml:space="preserve", we are currently handing it at all. 

What we see is that the problem is with the first whitespace. MateCat replaces double spaces with a whitespace and an &nbsp; character. When white spaces are at the beginning and at the end of the line the browser removes them. 

So you would see one whitespace when there are two at the beginning of the line, but you would see three spaces when there are four whitespaces. Only the first whitespace at beginning of line is removed. 

We are discussing possible solutions for this problem and will let you know.

**Comment by Lilimopps** [comment]
Hi Team. Any updates about this issue?

**Comment by freegenie** [comment]
this commit should fix the issue 3c034beb5, it went online few minutes ago.

**Comment by Lilimopps** [comment]
It works, thank you!
