### ISSUE TITLE
ModernMT integration 

### ISSUE THREAD

**Issue by mehmedes** [matecat/MateCat#848]
Is it possible to integrate my ModernMT server into my Matecat installation?

**Comment by mzeidhassan** [comment]
Hi all, 
I second this enhancement. Any plans to create a connector for ModernMT? ModernMT is reliable, stable and REST-ready. I hope you release a connector for it in the near future.

Thanks!

**Comment by Ostico** [comment]
https://github.com/matecat/MateCat/issues/992

**Comment by Ostico** [comment]
Currently in test.

**Comment by mzeidhassan** [comment]
@Ostico Is MMT integration plugin available now in the open source version? I can see it now in the public version of MateCat. Please let us know!

**Comment by Ostico** [comment]
Yes, it is available.

**Comment by lennart-tondeleir** [comment]
If I log into MateCat and try adding an MMT engine to my test project I am asked to provide a license key? Is there a way to connect to my own local MMT engine? Or would that only work in the open source MateCat?

Looking forward to your response!

**Comment by mzeidhassan** [comment]
Hi @Ostico,

I hope there is away to connect to our local instance of MMT. It seems it's not possible now and you need to buy a licence for ModernMT. Since both MateCat and ModernMT are both open-source, I really think it makes sense to make the plugin for MMT open-source as well. As you know, this will be useful for people who have local instance and working on some confidential work that cannot be shared publicly. Please let me know what you think. 

Thanks again!

**Comment by magali-joine** [comment]
Looking for a way to include a local custom neural model into MateCat.

Reason: The language pair I'm using is not available otherwise. (chr_en, en_chr)

**Comment by Ostico** [comment]
Sorry, ModernMT is open source but it's Enterprise API layer ( to which MateCat communicate ) is not.

**Comment by magali-joine** [comment]
Isn't the REST API that the local running copy of modernmt presents the same or close? I know there is a translate API call via REST.

[modernmt API Documentation](https://github.com/modernmt/modernmt/wiki/API-Documentation)

**Comment by riccio82** [comment]
Integration done, it took us a while but it is available! :D
