### ISSUE TITLE
Projects created via the API do not appear in either Personal or Team management panel

### ISSUE THREAD

**Issue by robot-xliff-farmer** [matecat/MateCat#881]
Is there any way in the API to specify to which team the created project should belong to?

Currently all my projects created via http requests go to nowhere in terms of Management panel and uploaded TMXs are greyed out.

I can open the created project but TMs are not applied and when I tried to change a TM description, the error message 'TM key is not valid' appears.

What I'm doing wrong?

**Comment by Ostico** [comment]
Hi @robot-xliff-farmer , please call the support, they will create an api_token to instruct MateCat about who is the client. 
This is at moment not an automated task.

The created toke must be added to the client request header in order to identify the user.
```
x-matecat-key:XXXXXXXXXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXX
```

In this way, the created projects will be added to the user management panel and the TM keys will be visible to the user and used to get and fetch contributions.
