### ISSUE TITLE
Retention of files in Cache

### ISSUE THREAD

**Issue by mirko33** [matecat/MateCat#939]
Under which conditions is it OK to delete subfolders of the Cache folder? 

Maybe not an issue but still potentially useful for anyone to know who runs their own MateCat.

**Comment by Ostico** [comment]
Hi @mirko33 ,

the ```storage/files_storage/cache/``` subfolders contains the files already converted from a general doc format to the xliff and/or the original xliff files if no conversion was made. They are created and checked with the shasum of the files.

These files are HARD links to the files into the directory ```storage/files_storage/files``` to not waste space on disk.

The hard links in the cache directory can be safely deleted, of course NEVER delete the files in the **files** directory, they are needed to download the translations from MateCat.

Anyway, the files and directories in the **cache** folder do not consume space on disk because they are physically the same files in the **files** directory.

**Comment by mirko33** [comment]
Oh, thanks, hadn't noticed they were hard link :-(
