### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by laiviet** [matecat/MateCat#964]
I followed the tutorial at https://www.matecat.com/advanced-manual-setup/#ia
And got the following error

root@catserver:/home/matecat/cattool/lib/Model# mysql -u root -p < matecat.sql
Enter password: 
ERROR 1067 (42000) at line 920: Invalid default value for 'created_at'

Please check it. THank you so much

**Comment by emale999** [comment]
As of version 5.6 mySQL doesn't allow CUURRENT_TIMESTAMP as default value for DATETIME fields.
Maybe the 'teams.created_at' field should be altered to be a TIMESTAMP instead of a DATETIME?

@laiviet: I changed line 920 of matecat.sql to
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
and had no error after that.

But I can not say if that may have any negative effects when running matecat (at most when creating teams in admin interface, I guess).

**Comment by Ostico** [comment]
Hi all.
@emale999 it's not correct, MySQL **below** 5.6.5 doesn't allow to initialize ```DATETIME``` fields and set a default date value to CURRENT_TIMESTAMP.

Anyway, you're done the right thing, there are no negative effects, these fields are equivalent from PHP and MateCat perspective.
